"""answer.date added

Revision ID: 2051ea9fc5e4
Revises: 7ef0a8a2194b
Create Date: 2016-02-17 15:08:25.604592

"""

# revision identifiers, used by Alembic.
revision = '2051ea9fc5e4'
down_revision = '7ef0a8a2194b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_answers_date'), 'answers', ['date'], unique=False)
    op.create_index(op.f('ix_questions_current_value'), 'questions', ['current_value'], unique=False)
    op.create_index(op.f('ix_questions_solved'), 'questions', ['solved'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_solved'), table_name='questions')
    op.drop_index(op.f('ix_questions_current_value'), table_name='questions')
    op.drop_index(op.f('ix_answers_date'), table_name='answers')
    op.drop_column('answers', 'date')
    ### end Alembic commands ###
