"""Question.accepted_id

Revision ID: 7ef0a8a2194b
Revises: 092344d4ec34
Create Date: 2016-02-11 18:49:34.204553

"""

# revision identifiers, used by Alembic.
revision = '7ef0a8a2194b'
down_revision = '092344d4ec34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('accepted_id', sa.Integer(), nullable=True))
    op.drop_index('ix_questions_title', table_name='questions')
    op.create_index(op.f('ix_questions_title'), 'questions', ['title'], unique=False)
    op.drop_constraint('questions_accepted_answer_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'answers', ['accepted_id'], ['id'])
    op.drop_column('questions', 'accepted_answer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('accepted_answer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_accepted_answer_fkey', 'questions', 'answers', ['accepted_answer'], ['id'])
    op.drop_index(op.f('ix_questions_title'), table_name='questions')
    op.create_index('ix_questions_title', 'questions', ['title'], unique=True)
    op.drop_column('questions', 'accepted_id')
    ### end Alembic commands ###
